"""empty message

Revision ID: 15db6e0e6daa
Revises: bd2e62245356
Create Date: 2020-01-14 11:03:39.636491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15db6e0e6daa'
down_revision = 'bd2e62245356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_object')
    # ### end Alembic commands ###
